import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, chownSync, chmodSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, basename } from "node:path";
import { type Config, type PiNode, saveConfig, tftpDir, nfsDir } from "./config.ts";
import { $, $quiet, $try, log, sleep, onCleanup, removeCleanup } from "./shell.ts";
import { configureNetwork } from "./network.ts";

// ── Shared helpers ──────────────────────────────────────────────────────────

function cmdline(config: Config, nfsPath: string): string {
  return `console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=${config.lan_ip}:${nfsPath},nfsvers=3 rw ip=dhcp rootwait`;
}

function fstab(config: Config, nfsPath: string, tftpPath: string): string {
  return `# Netboot fstab — generated by piboot
proc            /proc   proc    defaults          0 0
${config.lan_ip}:${nfsPath}  /     nfs  defaults,noatime,nfsvers=3  0 1
${config.lan_ip}:${tftpPath}  /boot/firmware  nfs  defaults,noatime,nfsvers=3  0 2
tmpfs           /tmp    tmpfs   defaults,nosuid   0 0
tmpfs           /var/tmp tmpfs  defaults,nosuid   0 0
`;
}

function writeDnsmasqConf(config: Config): void {
  const nodeLeases = config.nodes
    .map((n) => `dhcp-host=${n.mac},${n.ip},${n.hostname},infinite`)
    .join("\n");

  writeFileSync("/etc/dnsmasq.conf",
`# ── Interface ────────────────────────────────
interface=${config.lan_if}
bind-interfaces
except-interface=lo

# ── DNS (forward upstream) ───────────────────
server=1.1.1.1
server=8.8.8.8

# ── DHCP ─────────────────────────────────────
dhcp-range=${config.dhcp_range_start},${config.dhcp_range_end},${config.lan_mask},${config.dhcp_lease}
dhcp-option=option:router,${config.lan_ip}
dhcp-option=option:dns-server,${config.lan_ip}

# ── Static leases ────────────────────────────
${nodeLeases}

# ── TFTP / PXE (Raspberry Pi netboot) ───────
enable-tftp
tftp-root=${config.tftp_root}
pxe-service=0,"Raspberry Pi Boot"

# ── Logging ──────────────────────────────────
log-dhcp
log-facility=/var/log/dnsmasq.log
`);
}

function writeNfsExports(config: Config): void {
  const entries = config.nodes.flatMap((n) => {
    const nfs = nfsDir(config, n.hostname);
    const tftp = tftpDir(config, n.serial);
    return [
      `${nfs}   ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)`,
      `${tftp}  ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)`,
    ];
  });

  writeFileSync("/etc/exports",
`# Netboot exports — managed by piboot
${entries.join("\n")}
`);
}

async function ensureIptablesRule(rule: string): Promise<void> {
  const result = await $try(`iptables -C ${rule} 2>/dev/null && echo EXISTS`);
  if (result.trim() === "EXISTS") return;
  await $(`iptables -A ${rule}`);
}

function findSshPubKey(path?: string): string | null {
  if (path && path !== "true") {
    if (!existsSync(path)) log.fail(`SSH key not found: ${path}`);
    return readFileSync(path, "utf-8").trim();
  }
  // Auto-detect: try common public key locations
  const home = process.env.HOME ?? "/root";
  for (const name of ["id_ed25519.pub", "id_rsa.pub", "id_ecdsa.pub"]) {
    const p = join(home, ".ssh", name);
    if (existsSync(p)) {
      log.info(`Using SSH key: ${p}`);
      return readFileSync(p, "utf-8").trim();
    }
  }
  log.fail(
    `No SSH public key found. Generate one with: ssh-keygen -t ed25519\n` +
    `       Or specify a path: --ssh-key /path/to/key.pub`
  );
}

/** Find the server's SSH public key (for management access to nodes) */
function findServerKey(): string | null {
  const home = process.env.HOME ?? "/root";
  for (const name of ["id_ed25519.pub", "id_rsa.pub", "id_ecdsa.pub"]) {
    const p = join(home, ".ssh", name);
    if (existsSync(p)) return readFileSync(p, "utf-8").trim();
  }
  return null;
}

function installSshKeys(nfsRoot: string, userKey?: string | null): void {
  const keys: string[] = [];

  // Always install the server's key for management (reboot, diagnostics)
  const serverKey = findServerKey();
  if (serverKey) keys.push(serverKey);

  // Install user-provided key if different from server key
  if (userKey && userKey !== serverKey) keys.push(userKey);

  if (keys.length === 0) return;

  const sshDir = join(nfsRoot, "home/pi/.ssh");
  mkdirSync(sshDir, { recursive: true });
  writeFileSync(join(sshDir, "authorized_keys"), keys.join("\n") + "\n");

  // Set ownership to pi (uid 1000) — chown works on the NFS root directly
  chownSync(sshDir, 1000, 1000);
  chmodSync(sshDir, 0o700);
  chownSync(join(sshDir, "authorized_keys"), 1000, 1000);
  chmodSync(join(sshDir, "authorized_keys"), 0o600);

  // Disable password auth when key auth is available
  const sshdConf = join(nfsRoot, "etc/ssh/sshd_config.d/piboot.conf");
  mkdirSync(join(nfsRoot, "etc/ssh/sshd_config.d"), { recursive: true });
  writeFileSync(sshdConf, "PasswordAuthentication no\n");

  log.info(`SSH key auth configured (${keys.length} key${keys.length > 1 ? "s" : ""}), password auth disabled`);
}

async function patchNfsRoot(config: Config, node: PiNode, sshKey?: string | null): Promise<void> {
  const nfs = nfsDir(config, node.hostname);
  const tftp = tftpDir(config, node.serial);

  // fstab
  writeFileSync(join(nfs, "etc/fstab"), fstab(config, nfs, tftp));

  // hostname
  writeFileSync(join(nfs, "etc/hostname"), node.hostname + "\n");
  const hosts = readFileSync(join(nfs, "etc/hosts"), "utf-8");
  writeFileSync(
    join(nfs, "etc/hosts"),
    hosts.replace(/127\.0\.1\.1.*/g, `127.0.1.1\t${node.hostname}`)
  );

  // SSH — enable and pre-generate host keys so sshd works immediately on boot
  writeFileSync(join(nfs, "boot/firmware/ssh"), "");
  writeFileSync(join(tftp, "ssh"), "");
  for (const type of ["rsa", "ecdsa", "ed25519"]) {
    const keyPath = join(nfs, `etc/ssh/ssh_host_${type}_key`);
    if (!existsSync(keyPath)) {
      await $quiet(`ssh-keygen -t ${type} -f "${keyPath}" -N "" -q`);
    }
  }

  // Default user: pi/raspberry
  const hash = await $quiet("echo 'raspberry' | openssl passwd -6 -stdin");
  writeFileSync(join(tftp, "userconf.txt"), `pi:${hash}\n`);
  writeFileSync(join(nfs, "boot/firmware/userconf.txt"), `pi:${hash}\n`);

  // Strip init= from cmdline
  if (existsSync(join(tftp, "cmdline.txt"))) {
    const cl = readFileSync(join(tftp, "cmdline.txt"), "utf-8");
    writeFileSync(join(tftp, "cmdline.txt"), cl.replace(/ init=[^ ]*/g, ""));
  }

  // Disable SD-card services
  for (const svc of ["resize2fs_once", "dphys-swapfile"]) {
    const wantsLink = join(nfs, `etc/systemd/system/multi-user.target.wants/${svc}.service`);
    const maskLink = join(nfs, `etc/systemd/system/${svc}.service`);
    if (existsSync(wantsLink)) rmSync(wantsLink, { force: true });
    await $try(`ln -sf /dev/null "${maskLink}"`);
  }

  // First-boot auto-update service
  const firstBootService = `[Unit]
Description=First boot system update
After=network-online.target
Wants=network-online.target
ConditionPathExists=/var/lib/piboot-first-boot

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'apt-get update && apt-get upgrade -y && rm /var/lib/piboot-first-boot'
ExecStart=/bin/systemctl disable piboot-first-update.service

[Install]
WantedBy=multi-user.target
`;
  writeFileSync(join(nfs, "etc/systemd/system/piboot-first-update.service"), firstBootService);
  writeFileSync(join(nfs, "var/lib/piboot-first-boot"), ""); // marker file
  // Enable the service
  mkdirSync(join(nfs, "etc/systemd/system/multi-user.target.wants"), { recursive: true });
  await $try(`ln -sf /etc/systemd/system/piboot-first-update.service "${join(nfs, "etc/systemd/system/multi-user.target.wants/piboot-first-update.service")}"`);

  // SSH key auth — always install server key for management, plus user key if provided
  installSshKeys(nfs, sshKey);

  // Passwordless sudo for pi user (needed for remote reboot)
  writeFileSync(join(nfs, "etc/sudoers.d/010_pi-nopasswd"), "pi ALL=(ALL) NOPASSWD: ALL\n");
  chmodSync(join(nfs, "etc/sudoers.d/010_pi-nopasswd"), 0o440);

  log.info(`Patches applied → ${node.hostname}`);
}

/** Find serial by scanning TFTP dirs for cmdline.txt referencing the hostname */
function findSerialByHostname(config: Config, hostname: string): string | null {
  if (!existsSync(config.tftp_root)) return null;

  const dirs = readdirSync(config.tftp_root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const serial of dirs) {
    const cmdlinePath = join(config.tftp_root, serial, "cmdline.txt");
    if (existsSync(cmdlinePath)) {
      const content = readFileSync(cmdlinePath, "utf-8");
      // cmdline contains nfsroot=IP:/srv/nfs/HOSTNAME
      if (content.includes(`/${hostname},`) || content.includes(`/${hostname} `)) {
        return serial;
      }
    }
  }
  return null;
}

async function extractImage(config: Config, targetNfs: string, targetTftp: string): Promise<void> {
  if (!existsSync(config.image_raw)) {
    log.fail(`Base image not found: ${config.image_raw} — run 'piboot init' first`);
  }

  const loopDev = await $quiet(`losetup --show -fP "${config.image_raw}"`);
  await $(`kpartx -a "${loopDev}"`, { silent: true });
  const loopBase = basename(loopDev);
  await sleep(1000);

  const bootPart = `/dev/mapper/${loopBase}p1`;
  const rootPart = `/dev/mapper/${loopBase}p2`;

  let extractionComplete = false;

  const cleanup = async () => {
    await $try('umount /mnt/rpi_boot 2>/dev/null');
    await $try('umount /mnt/rpi_root 2>/dev/null');
    await $try(`kpartx -d "${loopDev}"`);
    await $try(`losetup -d "${loopDev}"`);

    // Remove partial directories if extraction didn't finish
    if (!extractionComplete) {
      if (existsSync(targetNfs)) {
        rmSync(targetNfs, { recursive: true, force: true });
        log.warn(`Removed partial NFS root: ${targetNfs}`);
      }
      if (existsSync(targetTftp)) {
        rmSync(targetTftp, { recursive: true, force: true });
        log.warn(`Removed partial TFTP dir: ${targetTftp}`);
      }
    }
  };
  onCleanup(cleanup);

  try {
    mkdirSync("/mnt/rpi_boot", { recursive: true });
    mkdirSync("/mnt/rpi_root", { recursive: true });
    await $(`mount -o ro "${rootPart}" /mnt/rpi_root`, { silent: true });
    await $(`mount -o ro "${bootPart}" /mnt/rpi_boot`, { silent: true });

    log.info("Copying rootfs (this takes a while) …");
    mkdirSync(targetNfs, { recursive: true });
    await $(`rsync -a /mnt/rpi_root/ "${targetNfs}/"`, { silent: true });

    mkdirSync(join(targetNfs, "boot/firmware"), { recursive: true });
    await $(`rsync -a /mnt/rpi_boot/ "${targetNfs}/boot/firmware/"`, { silent: true });

    log.info("Copying boot files …");
    mkdirSync(targetTftp, { recursive: true });
    await $(`rsync -a /mnt/rpi_boot/ "${targetTftp}/"`, { silent: true });

    extractionComplete = true;
  } finally {
    await cleanup();
    removeCleanup(cleanup);
  }
}

// ── Commands ────────────────────────────────────────────────────────────────

export async function init(config: Config, firstNode: PiNode, sshKeyPath?: string): Promise<void> {
  log.banner("PIBOOT — Netboot Server Init");

  // Validate SSH key upfront — fail fast before any heavy work
  const sshKey = sshKeyPath ? findSshPubKey(sshKeyPath) : null;

  // ── 1. Packages ──
  log.step(1, "Installing packages");
  await $(`apt-get update -qq`);
  await $(
    `DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ` +
    `dnsmasq nfs-kernel-server kpartx xz-utils wget iptables-persistent tcpdump rsync unzip`
  );

  // ── 2. Network ──
  log.step(2, `Configuring static IP on ${config.lan_if}`);
  await configureNetwork(config);

  // ── 3. Forwarding + NAT ──
  log.step(3, "Enabling IP forwarding and NAT");
  mkdirSync("/etc/sysctl.d", { recursive: true });
  writeFileSync("/etc/sysctl.d/99-netboot-forward.conf", "net.ipv4.ip_forward=1\n");
  await $(`sysctl -w net.ipv4.ip_forward=1`, { silent: true });

  await $(`iptables -t nat -F POSTROUTING`);
  await $(`iptables -t nat -A POSTROUTING -s ${config.lan_subnet}.0/24 -o ${config.wan_if} -j MASQUERADE`);
  await ensureIptablesRule(`FORWARD -i ${config.lan_if} -o ${config.wan_if} -j ACCEPT`);
  await ensureIptablesRule(`FORWARD -i ${config.wan_if} -o ${config.lan_if} -m state --state RELATED,ESTABLISHED -j ACCEPT`);
  await $try(`netfilter-persistent save`);
  log.info(`NAT: ${config.lan_subnet}.0/24 → ${config.wan_if}`);

  // ── 4. dnsmasq ──
  log.step(4, "Configuring dnsmasq (DHCP + TFTP + DNS)");
  await $try("systemctl stop dnsmasq");

  const resolvedActive = (await $try("systemctl is-active systemd-resolved")).trim();
  if (resolvedActive === "active") {
    log.warn("Stopping systemd-resolved (port 53 conflict)");
    await $(`systemctl stop systemd-resolved`);
    await $(`systemctl disable systemd-resolved`);
    writeFileSync("/etc/resolv.conf", "nameserver 1.1.1.1\nnameserver 8.8.8.8\n");
  }

  mkdirSync(config.tftp_root, { recursive: true });
  config.nodes.push(firstNode);
  saveConfig(config);
  writeDnsmasqConf(config);
  await $(`systemctl enable dnsmasq`);
  log.info(`DHCP ${config.dhcp_range_start}–${config.dhcp_range_end}, TFTP ${config.tftp_root}`);

  // ── 5. Download image ──
  log.step(5, "Downloading Raspberry Pi OS");
  if (!existsSync(config.image_raw)) {
    log.info(`URL: ${config.image_url}`);
    await $(`wget -q --show-progress -O "${config.image_file}" "${config.image_url}"`);
    log.info("Decompressing …");
    await $(`xz -d -k "${config.image_file}" -c > "${config.image_raw}"`);
    log.info(`Image ready: ${config.image_raw}`);
  } else {
    log.info(`Using existing image: ${config.image_raw}`);
  }

  // ── 6. Extract ──
  log.step(6, "Extracting boot + rootfs for first node");
  const piTftp = tftpDir(config, firstNode.serial);
  const piNfs = nfsDir(config, firstNode.hostname);
  if (existsSync(piNfs)) {
    log.warn(`NFS root already exists: ${piNfs} — skipping extraction. Use 'piboot reset ${firstNode.hostname}' to re-extract.`);
  } else {
    await extractImage(config, piNfs, piTftp);
  }

  // ── 7. Patch cmdline ──
  log.step(7, "Writing cmdline.txt");
  writeFileSync(join(piTftp, "cmdline.txt"), cmdline(config, piNfs) + "\n");

  // Kernel check
  if (!existsSync(join(piTftp, "kernel_2712.img"))) {
    log.warn("kernel_2712.img not in boot — Pi 5 may fall back to kernel8.img");
  }

  // ── 8. Patch rootfs ──
  log.step(8, "Patching NFS root");
  await patchNfsRoot(config, firstNode, sshKey);

  // ── 9. NFS exports ──
  log.step(9, "Configuring NFS server");
  mkdirSync("/etc/nfs.conf.d", { recursive: true });
  writeFileSync("/etc/nfs.conf.d/netboot.conf", "[nfsd]\nvers3=y\nvers4=y\n");

  writeNfsExports(config);

  await $(`exportfs -ra`);
  await $(`systemctl enable --now nfs-kernel-server`);
  await $(`systemctl restart nfs-kernel-server`);

  // ── 10. Start ──
  log.step(10, "Starting services");
  await $(`systemctl restart dnsmasq`);
  await $(`systemctl restart nfs-kernel-server`);

  // ── Save config ──
  saveConfig(config);

  // ── Done ──
  log.banner("NETBOOT SERVER READY");
  log.table([
    ["Server LAN IP", config.lan_ip],
    ["DHCP range", `${config.dhcp_range_start} – ${config.dhcp_range_end}`],
    ["Node", `${firstNode.hostname} → ${firstNode.ip} (${firstNode.mac})`],
    ["TFTP", piTftp],
    ["NFS root", piNfs],
    ["Default user", "pi / raspberry"],
  ]);
  console.log();
  log.info(`Watch logs:  tail -f /var/log/dnsmasq.log`);
  log.info(`SSH in:      ssh pi@${firstNode.ip}`);
}

export async function addNode(config: Config, node: PiNode, sshKeyPath?: string): Promise<void> {
  log.banner(`ADDING NODE: ${node.hostname}`);

  // Validate SSH key upfront — fail fast before image extraction
  const sshKey = sshKeyPath ? findSshPubKey(sshKeyPath) : null;

  const targetTftp = tftpDir(config, node.serial);
  const targetNfs = nfsDir(config, node.hostname);

  if (existsSync(targetNfs)) {
    log.fail(`NFS root already exists: ${targetNfs} — remove first or pick a different hostname`);
  }

  // Extract fresh from image
  log.step(1, "Extracting rootfs + boot from image");
  await extractImage(config, targetNfs, targetTftp);

  // Write cmdline
  log.step(2, "Writing cmdline.txt");
  writeFileSync(join(targetTftp, "cmdline.txt"), cmdline(config, targetNfs) + "\n");

  // Patch
  log.step(3, "Patching NFS root");
  await patchNfsRoot(config, node, sshKey);

  // DHCP + NFS — regenerate from config
  log.step(4, "Updating dnsmasq and NFS exports");
  config.nodes.push(node);
  writeDnsmasqConf(config);
  writeNfsExports(config);
  await $(`exportfs -ra`);
  await $(`systemctl restart dnsmasq`);

  // Save
  saveConfig(config);

  log.banner(`NODE ${node.hostname} READY`);
  log.table([
    ["Hostname", node.hostname],
    ["IP", node.ip],
    ["MAC", node.mac],
    ["Serial", node.serial],
    ["TFTP", targetTftp],
    ["NFS", targetNfs],
  ]);
  console.log();
  log.info(`Power it on and SSH: ssh pi@${node.ip}`);
}

export async function resetNode(config: Config, hostname: string, sshKeyPath?: string): Promise<void> {
  log.banner(`RESETTING NODE: ${hostname}`);

  // Validate SSH key upfront — fail fast before wiping rootfs
  const sshKey = sshKeyPath ? findSshPubKey(sshKeyPath) : null;

  const node = config.nodes.find((n) => n.hostname === hostname);
  if (!node) log.fail(`Node "${hostname}" not found in config. Run 'piboot list' to see nodes.`);

  const targetNfs = nfsDir(config, hostname);
  const targetTftp = tftpDir(config, node!.serial);

  if (!existsSync(config.image_raw)) {
    log.fail(`Base image not found: ${config.image_raw} — run 'piboot init' first`);
  }

  // Reboot the Pi before wiping — it's NFS-booting so cmdline.txt has
  // rootwait, meaning the kernel will retry the NFS mount until we finish.
  // Test connectivity first, then send reboot (reboot itself drops the connection).
  log.step(1, "Rebooting node");
  const sshAlive = await $try(
    `ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes pi@${node!.ip} "echo OK" 2>/dev/null`
  );
  let rebooted = false;
  if (sshAlive.trim() === "OK") {
    await $try(
      `ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes pi@${node!.ip} "sudo reboot" 2>/dev/null`
    );
    rebooted = true;
    log.info(`Reboot signal sent to ${node!.ip} — Pi will boot into fresh rootfs automatically`);
    await sleep(3000); // give the Pi a moment to start shutting down
  } else {
    log.warn(`Could not SSH into ${node!.ip} — you may need to power cycle after reset`);
  }

  // Wipe
  log.step(2, "Wiping rootfs");
  rmSync(targetNfs, { recursive: true, force: true });

  // Re-extract
  log.step(3, "Re-extracting from image");
  await extractImage(config, targetNfs, targetTftp);

  // Cmdline
  log.step(4, "Writing cmdline.txt");
  writeFileSync(join(targetTftp, "cmdline.txt"), cmdline(config, targetNfs) + "\n");

  // Patch
  log.step(5, "Patching NFS root");
  await patchNfsRoot(config, node!, sshKey);

  log.banner(`NODE ${hostname} RESET TO FACTORY`);
  if (rebooted) {
    log.info("Pi is rebooting — it will come up with the fresh rootfs automatically.");
  } else {
    log.info("Power cycle the Pi to boot into the fresh rootfs.");
  }
}

export async function removeNode(config: Config, hostname: string): Promise<void> {
  log.banner(`REMOVING NODE: ${hostname}`);

  const node = config.nodes.find((n) => n.hostname === hostname);
  // If node not in config, try to find serial by scanning TFTP directories
  const serial = node?.serial ?? findSerialByHostname(config, hostname);
  const targetNfs = nfsDir(config, hostname);

  // Reboot the Pi so it drops into the bootloader waiting for TFTP
  if (node) {
    log.step(1, "Rebooting node");
    const sshAlive = await $try(
      `ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes pi@${node.ip} "echo OK" 2>/dev/null`
    );
    if (sshAlive.trim() === "OK") {
      await $try(
        `ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes pi@${node.ip} "sudo reboot" 2>/dev/null`
      );
      log.info(`Reboot signal sent to ${node.ip} — Pi will wait in bootloader for re-provisioning`);
      await sleep(3000);
    } else {
      log.warn(`Could not SSH into ${node.ip} — node may be offline already`);
    }
  }

  // Remove NFS root
  if (existsSync(targetNfs)) {
    rmSync(targetNfs, { recursive: true, force: true });
    log.info(`Deleted NFS root: ${targetNfs}`);
  } else {
    log.warn(`NFS root not found: ${targetNfs}`);
  }

  // Remove TFTP
  if (serial) {
    const targetTftp = tftpDir(config, serial);
    if (existsSync(targetTftp)) {
      rmSync(targetTftp, { recursive: true, force: true });
      log.info(`Deleted TFTP dir: ${targetTftp}`);
    }
  } else {
    log.warn(`Could not determine serial for ${hostname} — TFTP dir may need manual cleanup`);
  }

  // Regenerate dnsmasq.conf and exports without this node
  config.nodes = config.nodes.filter((n) => n.hostname !== hostname);
  writeDnsmasqConf(config);
  writeNfsExports(config);
  await $try("exportfs -ra");
  await $try("systemctl restart dnsmasq");
  saveConfig(config);
  log.info(`Removed DHCP reservation and NFS exports`);
}

export function listNodes(config: Config): void {
  if (config.nodes.length === 0) {
    log.warn("No nodes configured. Run 'piboot init' to set up the first node.");
    return;
  }

  console.log();
  const header = [
    "HOSTNAME".padEnd(16),
    "IP".padEnd(16),
    "MAC".padEnd(20),
    "SERIAL".padEnd(10),
    "NFS",
  ].join("  ");
  console.log(`  \x1b[1m${header}\x1b[0m`);
  console.log(`  ${"─".repeat(header.length)}`);

  for (const node of config.nodes) {
    const nfs = nfsDir(config, node.hostname);
    const exists = existsSync(nfs) ? "\x1b[32m✓\x1b[0m" : "\x1b[31m✗\x1b[0m";
    console.log(
      `  ${node.hostname.padEnd(16)}  ${node.ip.padEnd(16)}  ${node.mac.padEnd(20)}  ${node.serial.padEnd(10)}  ${exists}`
    );
  }
  console.log();
}

export async function status(config: Config): Promise<void> {
  log.banner("PIBOOT STATUS");

  // Server info
  log.table([
    ["LAN interface", `${config.lan_if} → ${config.lan_ip}`],
    ["WAN interface", config.wan_if],
    ["TFTP root", config.tftp_root],
    ["NFS root", config.nfs_root],
    ["Base image", existsSync(config.image_raw) ? `${config.image_raw} ✓` : "NOT FOUND"],
    ["Nodes", String(config.nodes.length)],
  ]);

  // Service status
  console.log();
  for (const svc of ["dnsmasq", "nfs-kernel-server"]) {
    const st = (await $try(`systemctl is-active ${svc}`)).trim();
    const icon = st === "active" ? "\x1b[32m●\x1b[0m" : "\x1b[31m●\x1b[0m";
    console.log(`  ${icon}  ${svc}: ${st}`);
  }

  // Node table
  listNodes(config);
}

export async function logs(follow: boolean): Promise<void> {
  if (follow) {
    await $(`tail -f /var/log/dnsmasq.log`);
  } else {
    await $(`tail -50 /var/log/dnsmasq.log`);
  }
}

export function sshNode(config: Config, hostname: string, extraArgs: string[]): void {
  const node = config.nodes.find((n) => n.hostname === hostname);
  if (!node) {
    log.fail(`Node "${hostname}" not found. Run 'piboot list' to see nodes.`);
  }

  const args = ["pi@" + node!.ip, ...extraArgs];
  log.info(`ssh ${args.join(" ")}`);

  try {
    execFileSync("ssh", args, { stdio: "inherit" });
  } catch (err: any) {
    process.exit(err.status ?? 1);
  }
}

export async function doctor(config: Config): Promise<void> {
  log.banner("PIBOOT DOCTOR");

  let issues = 0;

  function pass(msg: string): void {
    console.log(`  \x1b[32m✓\x1b[0m  ${msg}`);
  }
  function fail(msg: string, fix?: string): void {
    issues++;
    console.log(`  \x1b[31m✗\x1b[0m  ${msg}`);
    if (fix) console.log(`      → ${fix}`);
  }

  // LAN interface IP
  const ipOut = await $try(`ip addr show ${config.lan_if} 2>/dev/null`);
  if (ipOut.includes(`inet ${config.lan_ip}/`)) {
    pass(`LAN interface ${config.lan_if} has ${config.lan_ip}`);
  } else {
    fail(
      `LAN interface ${config.lan_if} missing IP ${config.lan_ip}`,
      `Run: sudo ip addr add ${config.lan_ip}/24 dev ${config.lan_if}`
    );
  }

  // dnsmasq
  const dnsmasqActive = (await $try("systemctl is-active dnsmasq")).trim();
  if (dnsmasqActive === "active") {
    pass("dnsmasq: active");
  } else {
    fail("dnsmasq: " + dnsmasqActive, "Run: sudo systemctl restart dnsmasq");
  }

  const dnsmasqTest = await $try("dnsmasq --test 2>&1");
  if (dnsmasqTest.includes("syntax check OK")) {
    pass("dnsmasq config: valid");
  } else {
    fail("dnsmasq config: invalid", "Check: dnsmasq --test");
  }

  // NFS
  const nfsActive = (await $try("systemctl is-active nfs-kernel-server")).trim();
  if (nfsActive === "active") {
    pass("nfs-kernel-server: active");
  } else {
    fail("nfs-kernel-server: " + nfsActive, "Run: sudo systemctl restart nfs-kernel-server");
  }

  // IP forwarding
  const fwd = (await $try("sysctl -n net.ipv4.ip_forward")).trim();
  if (fwd === "1") {
    pass("IP forwarding: enabled");
  } else {
    fail("IP forwarding: disabled", "Run: sudo sysctl -w net.ipv4.ip_forward=1");
  }

  // NAT rule
  const natCheck = await $try(
    `iptables -t nat -C POSTROUTING -s ${config.lan_subnet}.0/24 -o ${config.wan_if} -j MASQUERADE 2>/dev/null && echo EXISTS`
  );
  if (natCheck.trim() === "EXISTS") {
    pass(`NAT masquerade: ${config.lan_subnet}.0/24 → ${config.wan_if}`);
  } else {
    fail(
      "NAT masquerade rule missing",
      `Run: sudo iptables -t nat -A POSTROUTING -s ${config.lan_subnet}.0/24 -o ${config.wan_if} -j MASQUERADE`
    );
  }

  // Per-node checks
  const exportsList = await $try("cat /etc/exports 2>/dev/null");

  for (const node of config.nodes) {
    const tftp = tftpDir(config, node.serial);
    const nfs = nfsDir(config, node.hostname);

    if (existsSync(join(tftp, "cmdline.txt"))) {
      pass(`Node ${node.hostname}: TFTP dir OK (${node.serial})`);
    } else {
      fail(
        `Node ${node.hostname}: TFTP dir missing or no cmdline.txt`,
        `Check: ls ${tftp}/`
      );
    }

    if (existsSync(join(tftp, "kernel_2712.img")) || existsSync(join(tftp, "kernel8.img"))) {
      pass(`Node ${node.hostname}: kernel image present`);
    } else {
      fail(
        `Node ${node.hostname}: no kernel image in TFTP dir`,
        `May need: piboot reset ${node.hostname}`
      );
    }

    if (existsSync(join(nfs, "etc")) && existsSync(join(nfs, "bin"))) {
      pass(`Node ${node.hostname}: NFS root OK`);
    } else {
      fail(
        `Node ${node.hostname}: NFS root missing or incomplete`,
        `Run: piboot reset ${node.hostname}`
      );
    }

    if (exportsList.includes(nfs)) {
      pass(`Node ${node.hostname}: NFS exports present`);
    } else {
      fail(
        `Node ${node.hostname}: missing from /etc/exports`,
        `Run: sudo exportfs -ra (or any piboot add/remove will regenerate)`
      );
    }
  }

  // Orphan detection
  if (existsSync(config.tftp_root)) {
    const tftpDirs = readdirSync(config.tftp_root, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
    const knownSerials = new Set(config.nodes.map((n) => n.serial));
    for (const dir of tftpDirs) {
      if (!knownSerials.has(dir)) {
        fail(
          `Orphaned TFTP dir: ${join(config.tftp_root, dir)} (no matching node in config)`,
          "If unused, manually remove it"
        );
      }
    }
  }

  if (existsSync(config.nfs_root)) {
    const nfsDirs = readdirSync(config.nfs_root, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
    const knownHostnames = new Set(config.nodes.map((n) => n.hostname));
    for (const dir of nfsDirs) {
      if (!knownHostnames.has(dir)) {
        fail(
          `Orphaned NFS dir: ${join(config.nfs_root, dir)} (no matching node in config)`,
          `If unused: piboot remove ${dir}`
        );
      }
    }
  }

  // Summary
  console.log();
  if (issues === 0) {
    log.info("All checks passed.");
  } else {
    log.warn(`${issues} issue${issues > 1 ? "s" : ""} found.`);
  }
}

const PIBOOT_REPO = "https://github.com/MAkcanca/piboot-cli.git";
const PIBOOT_DIR = "/opt/piboot";

export async function update(): Promise<void> {
  log.banner("PIBOOT UPDATE");

  if (existsSync(join(PIBOOT_DIR, ".git"))) {
    log.info("Pulling latest from GitHub...");
    await $(`git -C "${PIBOOT_DIR}" pull --ff-only origin main`);
  } else {
    log.info("Cloning piboot...");
    await $(`git clone "${PIBOOT_REPO}" "${PIBOOT_DIR}"`);
  }

  // Ensure wrapper script exists
  const wrapper = "/usr/local/bin/piboot";
  if (!existsSync(wrapper)) {
    writeFileSync(wrapper, '#!/bin/sh\nexec deno run --allow-all /opt/piboot/src/cli.ts "$@"\n');
    chmodSync(wrapper, 0o755);
    log.info("Created wrapper: /usr/local/bin/piboot");
  }

  log.info("Updated to latest version.");
}
