import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from "node:fs";
import { join, basename } from "node:path";
import { type Config, type PiNode, saveConfig, tftpDir, nfsDir } from "./config";
import { $, $quiet, $try, log, sleep } from "./shell";
import { configureNetwork } from "./network";

// ── Shared helpers ──────────────────────────────────────────────────────────

function cmdline(config: Config, nfsPath: string): string {
  return `console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=${config.lan_ip}:${nfsPath},nfsvers=3 rw ip=dhcp rootwait`;
}

function fstab(config: Config, nfsPath: string, tftpPath: string): string {
  return `# Netboot fstab — generated by piboot
proc            /proc   proc    defaults          0 0
${config.lan_ip}:${nfsPath}  /     nfs  defaults,noatime,nfsvers=3  0 1
${config.lan_ip}:${tftpPath}  /boot/firmware  nfs  defaults,noatime,nfsvers=3  0 2
tmpfs           /tmp    tmpfs   defaults,nosuid   0 0
tmpfs           /var/tmp tmpfs  defaults,nosuid   0 0
`;
}

async function patchNfsRoot(config: Config, node: PiNode): Promise<void> {
  const nfs = nfsDir(config, node.hostname);
  const tftp = tftpDir(config, node.serial);

  // fstab
  writeFileSync(join(nfs, "etc/fstab"), fstab(config, nfs, tftp));

  // hostname
  writeFileSync(join(nfs, "etc/hostname"), node.hostname + "\n");
  const hosts = readFileSync(join(nfs, "etc/hosts"), "utf-8");
  writeFileSync(
    join(nfs, "etc/hosts"),
    hosts.replace(/127\.0\.1\.1.*/g, `127.0.1.1\t${node.hostname}`)
  );

  // SSH
  writeFileSync(join(nfs, "boot/firmware/ssh"), "");
  writeFileSync(join(tftp, "ssh"), "");

  // Default user: pi/raspberry
  const hash = await $quiet("echo 'raspberry' | openssl passwd -6 -stdin");
  writeFileSync(join(tftp, "userconf.txt"), `pi:${hash}\n`);
  writeFileSync(join(nfs, "boot/firmware/userconf.txt"), `pi:${hash}\n`);

  // Strip init= from cmdline
  if (existsSync(join(tftp, "cmdline.txt"))) {
    const cl = readFileSync(join(tftp, "cmdline.txt"), "utf-8");
    writeFileSync(join(tftp, "cmdline.txt"), cl.replace(/ init=[^ ]*/g, ""));
  }

  // Disable SD-card services
  for (const svc of ["resize2fs_once", "dphys-swapfile"]) {
    const wantsLink = join(nfs, `etc/systemd/system/multi-user.target.wants/${svc}.service`);
    const maskLink = join(nfs, `etc/systemd/system/${svc}.service`);
    if (existsSync(wantsLink)) rmSync(wantsLink, { force: true });
    await $try(`ln -sf /dev/null "${maskLink}"`);
  }

  // First-boot auto-update service
  const firstBootService = `[Unit]
Description=First boot system update
After=network-online.target
Wants=network-online.target
ConditionPathExists=/var/lib/piboot-first-boot

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'apt-get update && apt-get upgrade -y && rm /var/lib/piboot-first-boot'
ExecStart=/bin/systemctl disable piboot-first-update.service

[Install]
WantedBy=multi-user.target
`;
  writeFileSync(join(nfs, "etc/systemd/system/piboot-first-update.service"), firstBootService);
  writeFileSync(join(nfs, "var/lib/piboot-first-boot"), ""); // marker file
  // Enable the service
  mkdirSync(join(nfs, "etc/systemd/system/multi-user.target.wants"), { recursive: true });
  await $try(`ln -sf /etc/systemd/system/piboot-first-update.service "${join(nfs, "etc/systemd/system/multi-user.target.wants/piboot-first-update.service")}"`);

  log.info(`Patches applied → ${node.hostname}`);
}

/** Find serial by scanning TFTP dirs for cmdline.txt referencing the hostname */
function findSerialByHostname(config: Config, hostname: string): string | null {
  if (!existsSync(config.tftp_root)) return null;

  const dirs = readdirSync(config.tftp_root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const serial of dirs) {
    const cmdlinePath = join(config.tftp_root, serial, "cmdline.txt");
    if (existsSync(cmdlinePath)) {
      const content = readFileSync(cmdlinePath, "utf-8");
      // cmdline contains nfsroot=IP:/srv/nfs/HOSTNAME
      if (content.includes(`/${hostname},`) || content.includes(`/${hostname} `)) {
        return serial;
      }
    }
  }
  return null;
}

async function extractImage(config: Config, targetNfs: string, targetTftp: string): Promise<void> {
  if (!existsSync(config.image_raw)) {
    log.fail(`Base image not found: ${config.image_raw} — run 'piboot init' first`);
  }

  const loopDev = await $quiet(`losetup --show -fP "${config.image_raw}"`);
  await $(`kpartx -a "${loopDev}"`, { silent: true });
  const loopBase = basename(loopDev);
  await sleep(1000);

  const bootPart = `/dev/mapper/${loopBase}p1`;
  const rootPart = `/dev/mapper/${loopBase}p2`;

  try {
    mkdirSync("/mnt/rpi_boot", { recursive: true });
    mkdirSync("/mnt/rpi_root", { recursive: true });
    await $(`mount -o ro "${rootPart}" /mnt/rpi_root`, { silent: true });
    await $(`mount -o ro "${bootPart}" /mnt/rpi_boot`, { silent: true });

    log.info("Copying rootfs (this takes a while) …");
    mkdirSync(targetNfs, { recursive: true });
    await $(`rsync -a /mnt/rpi_root/ "${targetNfs}/"`);

    mkdirSync(join(targetNfs, "boot/firmware"), { recursive: true });
    await $(`rsync -a /mnt/rpi_boot/ "${targetNfs}/boot/firmware/"`);

    log.info("Copying boot files …");
    mkdirSync(targetTftp, { recursive: true });
    await $(`rsync -a /mnt/rpi_boot/ "${targetTftp}/"`);
  } finally {
    await $try('umount /mnt/rpi_boot 2>/dev/null');
    await $try('umount /mnt/rpi_root 2>/dev/null');
    await $try(`kpartx -d "${loopDev}"`);
    await $try(`losetup -d "${loopDev}"`);
  }
}

// ── Commands ────────────────────────────────────────────────────────────────

export async function init(config: Config, firstNode: PiNode): Promise<void> {
  log.banner("PIBOOT — Netboot Server Init");

  // ── 1. Packages ──
  log.step(1, "Installing packages");
  await $(`apt-get update -qq`);
  await $(
    `DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ` +
    `dnsmasq nfs-kernel-server kpartx xz-utils wget iptables-persistent tcpdump rsync unzip`
  );

  // ── 2. Network ──
  log.step(2, `Configuring static IP on ${config.lan_if}`);
  await configureNetwork(config);

  // ── 3. Forwarding + NAT ──
  log.step(3, "Enabling IP forwarding and NAT");
  mkdirSync("/etc/sysctl.d", { recursive: true });
  writeFileSync("/etc/sysctl.d/99-netboot-forward.conf", "net.ipv4.ip_forward=1\n");
  await $(`sysctl -w net.ipv4.ip_forward=1`, { silent: true });

  await $(`iptables -t nat -F POSTROUTING`);
  await $(`iptables -t nat -A POSTROUTING -s ${config.lan_subnet}.0/24 -o ${config.wan_if} -j MASQUERADE`);
  await $try(`iptables -C FORWARD -i ${config.lan_if} -o ${config.wan_if} -j ACCEPT`);
  await $try(`iptables -C FORWARD -i ${config.wan_if} -o ${config.lan_if} -m state --state RELATED,ESTABLISHED -j ACCEPT`);
  await $try(`iptables -A FORWARD -i ${config.lan_if} -o ${config.wan_if} -j ACCEPT`);
  await $try(`iptables -A FORWARD -i ${config.wan_if} -o ${config.lan_if} -m state --state RELATED,ESTABLISHED -j ACCEPT`);
  await $try(`netfilter-persistent save`);
  log.info(`NAT: ${config.lan_subnet}.0/24 → ${config.wan_if}`);

  // ── 4. dnsmasq ──
  log.step(4, "Configuring dnsmasq (DHCP + TFTP + DNS)");
  await $try("systemctl stop dnsmasq");

  const resolvedActive = (await $try("systemctl is-active systemd-resolved")).trim();
  if (resolvedActive === "active") {
    log.warn("Stopping systemd-resolved (port 53 conflict)");
    await $(`systemctl stop systemd-resolved`);
    await $(`systemctl disable systemd-resolved`);
    writeFileSync("/etc/resolv.conf", "nameserver 1.1.1.1\nnameserver 8.8.8.8\n");
  }

  mkdirSync(config.tftp_root, { recursive: true });

  writeFileSync("/etc/dnsmasq.conf",
`# ── Interface ────────────────────────────────
interface=${config.lan_if}
bind-interfaces
except-interface=lo

# ── DNS (forward upstream) ───────────────────
server=1.1.1.1
server=8.8.8.8

# ── DHCP ─────────────────────────────────────
dhcp-range=${config.dhcp_range_start},${config.dhcp_range_end},${config.lan_mask},${config.dhcp_lease}
dhcp-option=option:router,${config.lan_ip}
dhcp-option=option:dns-server,${config.lan_ip}

# Static lease — first node
dhcp-host=${firstNode.mac},${firstNode.ip},${firstNode.hostname},infinite

# ── TFTP / PXE (Raspberry Pi netboot) ───────
enable-tftp
tftp-root=${config.tftp_root}
pxe-service=0,"Raspberry Pi Boot"

# ── Logging ──────────────────────────────────
log-dhcp
log-facility=/var/log/dnsmasq.log
`);

  await $(`systemctl enable dnsmasq`);
  log.info(`DHCP ${config.dhcp_range_start}–${config.dhcp_range_end}, TFTP ${config.tftp_root}`);

  // ── 5. Download image ──
  log.step(5, "Downloading Raspberry Pi OS");
  if (!existsSync(config.image_raw)) {
    log.info(`URL: ${config.image_url}`);
    await $(`wget -q --show-progress -O "${config.image_file}" "${config.image_url}"`);
    log.info("Decompressing …");
    await $(`xz -d -k "${config.image_file}" -c > "${config.image_raw}"`);
    log.info(`Image ready: ${config.image_raw}`);
  } else {
    log.info(`Using existing image: ${config.image_raw}`);
  }

  // ── 6. Extract ──
  log.step(6, "Extracting boot + rootfs for first node");
  const piTftp = tftpDir(config, firstNode.serial);
  const piNfs = nfsDir(config, firstNode.hostname);
  await extractImage(config, piNfs, piTftp);

  // ── 7. Patch cmdline ──
  log.step(7, "Writing cmdline.txt");
  writeFileSync(join(piTftp, "cmdline.txt"), cmdline(config, piNfs) + "\n");

  // Kernel check
  if (!existsSync(join(piTftp, "kernel_2712.img"))) {
    log.warn("kernel_2712.img not in boot — Pi 5 may fall back to kernel8.img");
  }

  // ── 8. Patch rootfs ──
  log.step(8, "Patching NFS root");
  await patchNfsRoot(config, firstNode);

  // ── 9. NFS exports ──
  log.step(9, "Configuring NFS server");
  mkdirSync("/etc/nfs.conf.d", { recursive: true });
  writeFileSync("/etc/nfs.conf.d/netboot.conf", "[nfsd]\nvers3=y\nvers4=y\n");

  writeFileSync("/etc/exports",
`# Netboot exports — managed by piboot
${piNfs}   ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)
${piTftp}  ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)
`);

  await $(`exportfs -ra`);
  await $(`systemctl enable --now nfs-kernel-server`);
  await $(`systemctl restart nfs-kernel-server`);

  // ── 10. Start ──
  log.step(10, "Starting services");
  await $(`systemctl restart dnsmasq`);
  await $(`systemctl restart nfs-kernel-server`);

  // ── Save config ──
  config.nodes.push(firstNode);
  saveConfig(config);

  // ── Done ──
  log.banner("NETBOOT SERVER READY");
  log.table([
    ["Server LAN IP", config.lan_ip],
    ["DHCP range", `${config.dhcp_range_start} – ${config.dhcp_range_end}`],
    ["Node", `${firstNode.hostname} → ${firstNode.ip} (${firstNode.mac})`],
    ["TFTP", piTftp],
    ["NFS root", piNfs],
    ["Default user", "pi / raspberry"],
  ]);
  console.log();
  log.info(`Watch logs:  tail -f /var/log/dnsmasq.log`);
  log.info(`SSH in:      ssh pi@${firstNode.ip}`);
}

export async function addNode(config: Config, node: PiNode): Promise<void> {
  log.banner(`ADDING NODE: ${node.hostname}`);

  const targetTftp = tftpDir(config, node.serial);
  const targetNfs = nfsDir(config, node.hostname);

  if (existsSync(targetNfs)) {
    log.fail(`NFS root already exists: ${targetNfs} — remove first or pick a different hostname`);
  }

  // Extract fresh from image
  log.step(1, "Extracting rootfs + boot from image");
  await extractImage(config, targetNfs, targetTftp);

  // Write cmdline
  log.step(2, "Writing cmdline.txt");
  writeFileSync(join(targetTftp, "cmdline.txt"), cmdline(config, targetNfs) + "\n");

  // Patch
  log.step(3, "Patching NFS root");
  await patchNfsRoot(config, node);

  // DHCP reservation
  log.step(4, "Adding DHCP reservation");
  const dnsmasq = readFileSync("/etc/dnsmasq.conf", "utf-8");
  writeFileSync(
    "/etc/dnsmasq.conf",
    dnsmasq.trimEnd() + `\ndhcp-host=${node.mac},${node.ip},${node.hostname},infinite\n`
  );

  // NFS exports
  log.step(5, "Adding NFS exports");
  const exports = readFileSync("/etc/exports", "utf-8");
  writeFileSync(
    "/etc/exports",
    exports.trimEnd() +
    `\n${targetNfs}   ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)` +
    `\n${targetTftp}  ${config.lan_subnet}.0/24(rw,sync,no_subtree_check,no_root_squash)\n`
  );
  await $(`exportfs -ra`);
  await $(`systemctl restart dnsmasq`);

  // Save
  config.nodes.push(node);
  saveConfig(config);

  log.banner(`NODE ${node.hostname} READY`);
  log.table([
    ["Hostname", node.hostname],
    ["IP", node.ip],
    ["MAC", node.mac],
    ["Serial", node.serial],
    ["TFTP", targetTftp],
    ["NFS", targetNfs],
  ]);
  console.log();
  log.info(`Power it on and SSH: ssh pi@${node.ip}`);
}

export async function resetNode(config: Config, hostname: string): Promise<void> {
  log.banner(`RESETTING NODE: ${hostname}`);

  const node = config.nodes.find((n) => n.hostname === hostname);
  if (!node) log.fail(`Node "${hostname}" not found in config. Run 'piboot list' to see nodes.`);

  const targetNfs = nfsDir(config, hostname);
  const targetTftp = tftpDir(config, node!.serial);

  if (!existsSync(config.image_raw)) {
    log.fail(`Base image not found: ${config.image_raw} — run 'piboot init' first`);
  }

  // Wipe
  log.step(1, "Wiping rootfs");
  rmSync(targetNfs, { recursive: true, force: true });

  // Re-extract
  log.step(2, "Re-extracting from image");
  await extractImage(config, targetNfs, targetTftp);

  // Cmdline
  log.step(3, "Writing cmdline.txt");
  writeFileSync(join(targetTftp, "cmdline.txt"), cmdline(config, targetNfs) + "\n");

  // Patch
  log.step(4, "Patching NFS root");
  await patchNfsRoot(config, node!);

  log.banner(`NODE ${hostname} RESET TO FACTORY`);
  log.info(`Power it on.`);
}

export async function removeNode(config: Config, hostname: string): Promise<void> {
  log.banner(`REMOVING NODE: ${hostname}`);

  const node = config.nodes.find((n) => n.hostname === hostname);
  // If node not in config, try to find serial by scanning TFTP directories
  const serial = node?.serial ?? findSerialByHostname(config, hostname);
  const targetNfs = nfsDir(config, hostname);

  // Remove NFS root
  if (existsSync(targetNfs)) {
    rmSync(targetNfs, { recursive: true, force: true });
    log.info(`Deleted NFS root: ${targetNfs}`);
  } else {
    log.warn(`NFS root not found: ${targetNfs}`);
  }

  // Remove TFTP
  if (serial) {
    const targetTftp = tftpDir(config, serial);
    if (existsSync(targetTftp)) {
      rmSync(targetTftp, { recursive: true, force: true });
      log.info(`Deleted TFTP dir: ${targetTftp}`);
    }
  } else {
    log.warn(`Could not determine serial for ${hostname} — TFTP dir may need manual cleanup`);
  }

  // Clean dnsmasq.conf
  if (existsSync("/etc/dnsmasq.conf")) {
    const dnsmasq = readFileSync("/etc/dnsmasq.conf", "utf-8");
    const filtered = dnsmasq
      .split("\n")
      .filter((line) => !line.includes(hostname))
      .join("\n");
    writeFileSync("/etc/dnsmasq.conf", filtered);
    await $try("systemctl restart dnsmasq");
    log.info("Removed DHCP reservation");
  }

  // Clean exports
  if (existsSync("/etc/exports")) {
    const exports = readFileSync("/etc/exports", "utf-8");
    const filtered = exports
      .split("\n")
      .filter((line) => !line.includes(hostname) && !(serial && line.includes(serial)))
      .join("\n");
    writeFileSync("/etc/exports", filtered);
    await $try("exportfs -ra");
    log.info("Removed NFS exports");
  }

  // Remove from config
  config.nodes = config.nodes.filter((n) => n.hostname !== hostname);
  saveConfig(config);

  log.info(`${hostname} fully removed.`);
}

export function listNodes(config: Config): void {
  if (config.nodes.length === 0) {
    log.warn("No nodes configured. Run 'piboot init' to set up the first node.");
    return;
  }

  console.log();
  const header = [
    "HOSTNAME".padEnd(16),
    "IP".padEnd(16),
    "MAC".padEnd(20),
    "SERIAL".padEnd(10),
    "NFS",
  ].join("  ");
  console.log(`  \x1b[1m${header}\x1b[0m`);
  console.log(`  ${"─".repeat(header.length)}`);

  for (const node of config.nodes) {
    const nfs = nfsDir(config, node.hostname);
    const exists = existsSync(nfs) ? "\x1b[32m✓\x1b[0m" : "\x1b[31m✗\x1b[0m";
    console.log(
      `  ${node.hostname.padEnd(16)}  ${node.ip.padEnd(16)}  ${node.mac.padEnd(20)}  ${node.serial.padEnd(10)}  ${exists}`
    );
  }
  console.log();
}

export async function status(config: Config): Promise<void> {
  log.banner("PIBOOT STATUS");

  // Server info
  log.table([
    ["LAN interface", `${config.lan_if} → ${config.lan_ip}`],
    ["WAN interface", config.wan_if],
    ["TFTP root", config.tftp_root],
    ["NFS root", config.nfs_root],
    ["Base image", existsSync(config.image_raw) ? `${config.image_raw} ✓` : "NOT FOUND"],
    ["Nodes", String(config.nodes.length)],
  ]);

  // Service status
  console.log();
  for (const svc of ["dnsmasq", "nfs-kernel-server"]) {
    const st = (await $try(`systemctl is-active ${svc}`)).trim();
    const icon = st === "active" ? "\x1b[32m●\x1b[0m" : "\x1b[31m●\x1b[0m";
    console.log(`  ${icon}  ${svc}: ${st}`);
  }

  // Node table
  listNodes(config);
}

export async function logs(follow: boolean): Promise<void> {
  if (follow) {
    await $(`tail -f /var/log/dnsmasq.log`);
  } else {
    await $(`tail -50 /var/log/dnsmasq.log`);
  }
}
